"""language.audio — audio record for a learning entry (SPEC §3.6).

Three audio_type values:
  recorded  — user-captured via browser microphone; stored immediately,
              status='completed', no async job.
  generated — TTS-generated by the audio service via edge-tts/espeak-ng;
              async job lifecycle: pending → processing → completed/failed.
  imported  — extracted from an Anki .apkg media bundle (M5);
              created directly with status='completed' by _create_audio_records().

Idempotency key: job_id (UUID) on generated/transcription jobs only.
UNIQUE constraint on (entry_id, audio_type, language) covers generated and
imported — prevents duplicate TTS jobs. recorded audio updates in-place via
Python create() override (last recording wins).
"""

import base64
import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)

LANGUAGE_SELECTION = [
    ('en', 'English'),
    ('uk', 'Ukrainian'),
    ('el', 'Greek'),
]

AUDIO_TYPE_SELECTION = [
    ('recorded', 'Recorded'),
    ('generated', 'Generated (TTS)'),
    ('imported', 'Imported (Anki)'),
]

# Separate job_id namespaces for generation vs transcription so a single
# audio record can track both lifecycles independently.
TRANSCRIPTION_JOB_PREFIX = 'tr-'


class LanguageAudio(models.Model):
    """Audio record linked to a single learning entry."""

    _name = 'language.audio'
    _description = 'Audio Recording / TTS'
    _inherit = ['language.job.status.mixin']
    _rec_name = 'audio_type'
    _order = 'entry_id, audio_type, language'

    entry_id = fields.Many2one(
        comodel_name='language.entry',
        string='Entry',
        required=True,
        ondelete='cascade',
        index=True,
    )
    audio_type = fields.Selection(
        selection=AUDIO_TYPE_SELECTION,
        string='Audio Type',
        required=True,
        index=True,
    )
    language = fields.Selection(
        selection=LANGUAGE_SELECTION,
        string='Language',
        required=True,
        index=True,
        help='Language of the audio content (may differ from entry source language for TTS).',
    )
    attachment_id = fields.Many2one(
        comodel_name='ir.attachment',
        string='Audio File',
        ondelete='set null',
        copy=False,
    )
    transcription = fields.Text(
        string='Transcription',
        readonly=True,
        copy=False,
        help='Speech-to-text result from faster-whisper (populated after transcription job).',
    )
    transcription_job_id = fields.Char(
        string='Transcription Job ID',
        readonly=True,
        copy=False,
        index=True,
        help='UUID for the audio.transcription.requested event (separate from TTS job_id).',
    )
    transcription_status = fields.Selection(
        selection=[
            ('none', 'Not transcribed'),
            ('pending', 'Pending'),
            ('processing', 'Processing'),
            ('completed', 'Completed'),
            ('failed', 'Failed'),
        ],
        string='Transcription Status',
        default='none',
        required=True,
        readonly=True,
        index=True,
    )
    transcription_error = fields.Text(
        string='Transcription Error',
        readonly=True,
        copy=False,
    )
    file_size_bytes = fields.Integer(
        string='File Size (bytes)',
        readonly=True,
        copy=False,
    )
    duration_seconds = fields.Float(
        string='Duration (s)',
        readonly=True,
        copy=False,
    )
    tts_engine = fields.Char(
        string='TTS Engine',
        readonly=True,
        copy=False,
        help='e.g. edge-tts, espeak-ng, piper. Blank for recorded/imported audio.',
    )

    _sql_constraints = [
        (
            'unique_entry_audio_type_language',
            'UNIQUE(entry_id, audio_type, language)',
            'An audio record already exists for this entry, type, and language.',
        ),
    ]

    # ------------------------------------------------------------------ #
    # Create override — recorded audio updates in-place (last wins)
    # ------------------------------------------------------------------ #

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('audio_type') == 'recorded':
                existing = self.search([
                    ('entry_id', '=', vals.get('entry_id')),
                    ('audio_type', '=', 'recorded'),
                    ('language', '=', vals.get('language')),
                ], limit=1)
                if existing:
                    old_attach = existing.attachment_id
                    existing.write({k: v for k, v in vals.items()
                                    if k not in ('entry_id', 'audio_type', 'language')})
                    if old_attach and old_attach != existing.attachment_id:
                        old_attach.sudo().unlink()
                    vals['_skip'] = existing.id
        new_vals = [v for v in vals_list if '_skip' not in v]
        records = super().create(new_vals) if new_vals else self.browse()
        skipped = self.browse([v['_skip'] for v in vals_list if '_skip' in v])
        return records | skipped

    # ------------------------------------------------------------------ #
    # Cron entry-point — drain result queues
    # ------------------------------------------------------------------ #

    def action_consume_results(self):
        """Drain audio result queues — called by scheduled cron."""
        from odoo.addons.language_core.models.rabbitmq_consumer import RabbitMQConsumer  # noqa: PLC0415
        consumer = RabbitMQConsumer(self.env)
        consumer.drain('audio.generation.completed', self._handle_generation_completed)
        consumer.drain('audio.generation.failed', self._handle_generation_failed)
        consumer.drain('audio.transcription.completed', self._handle_transcription_completed)
        consumer.drain('audio.transcription.failed', self._handle_transcription_failed)

    # ------------------------------------------------------------------ #
    # Lookup helpers
    # ------------------------------------------------------------------ #

    def _find_by_job_id(self, job_id):
        return self.sudo().search([('job_id', '=', job_id)], limit=1)

    def _find_by_transcription_job_id(self, job_id):
        return self.sudo().search([('transcription_job_id', '=', job_id)], limit=1)

    # ------------------------------------------------------------------ #
    # Result handlers — TTS generation
    # ------------------------------------------------------------------ #

    def _handle_generation_completed(self, job_id, payload):
        """Process an audio.generation.completed event.

        Creates an ir.attachment from the base64 audio in the payload,
        links it to the language.audio record, and marks status=completed.
        """
        record = self._find_by_job_id(job_id)
        if not record:
            _logger.warning('audio.generation.completed: no record for job_id=%s', job_id)
            return
        if record.status in ('completed', 'failed'):
            _logger.info(
                'audio.generation.completed: duplicate delivery job_id=%s (status=%s) — skipped',
                job_id, record.status,
            )
            return

        audio_b64 = payload.get('audio_b64', '')
        tts_engine = payload.get('tts_engine', '')
        file_size = payload.get('file_size_bytes', 0)

        attachment = None
        if audio_b64:
            fname = f'tts_{record.entry_id.id}_{record.language}.mp3'
            attachment = self.env['ir.attachment'].sudo().create({
                'name': fname,
                'datas': audio_b64,
                'res_model': 'language.audio',
                'res_id': record.id,
                'mimetype': 'audio/mpeg',
            })

        record.sudo().write({
            'status': 'completed',
            'attachment_id': attachment.id if attachment else False,
            'tts_engine': tts_engine,
            'file_size_bytes': file_size or (len(base64.b64decode(audio_b64)) if audio_b64 else 0),
            'error_message': False,
        })
        _logger.info('audio.generation.completed: job_id=%s entry=%d lang=%s engine=%s',
                     job_id, record.entry_id.id, record.language, tts_engine)

    def _handle_generation_failed(self, job_id, payload):
        """Process an audio.generation.failed event."""
        record = self._find_by_job_id(job_id)
        if not record:
            _logger.warning('audio.generation.failed: no record for job_id=%s', job_id)
            return
        if record.status in ('completed', 'failed'):
            _logger.info(
                'audio.generation.failed: duplicate delivery job_id=%s (status=%s) — skipped',
                job_id, record.status,
            )
            return
        record.sudo().write({
            'status': 'failed',
            'error_message': payload.get('error', 'Unknown error from audio service'),
        })
        _logger.warning('audio.generation.failed: job_id=%s error=%s', job_id, payload.get('error'))

    # ------------------------------------------------------------------ #
    # Result handlers — STT transcription
    # ------------------------------------------------------------------ #

    def _handle_transcription_completed(self, job_id, payload):
        """Process an audio.transcription.completed event."""
        record = self._find_by_transcription_job_id(job_id)
        if not record:
            _logger.warning('audio.transcription.completed: no record for job_id=%s', job_id)
            return
        if record.transcription_status in ('completed', 'failed'):
            _logger.info(
                'audio.transcription.completed: duplicate job_id=%s — skipped', job_id,
            )
            return
        record.sudo().write({
            'transcription': payload.get('transcription', ''),
            'transcription_status': 'completed',
            'transcription_error': False,
        })
        _logger.info('audio.transcription.completed: job_id=%s audio_id=%d',
                     job_id, record.id)

    def _handle_transcription_failed(self, job_id, payload):
        """Process an audio.transcription.failed event."""
        record = self._find_by_transcription_job_id(job_id)
        if not record:
            _logger.warning('audio.transcription.failed: no record for job_id=%s', job_id)
            return
        if record.transcription_status in ('completed', 'failed'):
            _logger.info(
                'audio.transcription.failed: duplicate job_id=%s — skipped', job_id,
            )
            return
        record.sudo().write({
            'transcription_status': 'failed',
            'transcription_error': payload.get('error', 'Unknown error'),
        })
        _logger.warning('audio.transcription.failed: job_id=%s error=%s',
                        job_id, payload.get('error'))

    # ------------------------------------------------------------------ #
    # Enqueue helpers (called from portal controller)
    # ------------------------------------------------------------------ #

    def _enqueue_tts(self, entry, language):
        """Enqueue a TTS generation job for the given entry and language.

        If a completed audio record already exists, returns it (lazy reuse).
        If a failed or missing record exists, resets it to pending and publishes.
        Returns the audio record (in pending or completed state).
        """
        existing = self.search([
            ('entry_id', '=', entry.id),
            ('audio_type', '=', 'generated'),
            ('language', '=', language),
        ], limit=1)

        if existing and existing.status == 'completed':
            return existing  # already generated — reuse

        from odoo.addons.language_core.models.rabbitmq_publisher import RabbitMQPublisher  # noqa: PLC0415
        publisher = RabbitMQPublisher(self.env)

        if existing:
            job_id = self._generate_job_id()
            existing.sudo().write({'status': 'pending', 'job_id': job_id,
                                   'error_message': False})
            audio_record = existing
        else:
            job_id = self._generate_job_id()
            audio_record = self.sudo().create({
                'entry_id': entry.id,
                'audio_type': 'generated',
                'language': language,
                'status': 'pending',
                'job_id': job_id,
            })

        payload = {
            'job_id': job_id,
            'entry_id': entry.id,
            'source_text': entry.source_text,
            'language': language,
        }
        publisher.publish('audio.generation.requested', payload, job_id)
        audio_record.sudo().write({'status': 'processing'})
        _logger.info('audio.generation.requested published: job_id=%s entry=%d lang=%s',
                     job_id, entry.id, language)
        return audio_record

    def _enqueue_transcription(self, audio_record):
        """Enqueue a transcription job for an existing recorded/generated audio record.

        Requires audio_record.attachment_id to be set. If not set, raises UserError.
        """
        from odoo.exceptions import UserError  # noqa: PLC0415
        if not audio_record.attachment_id:
            raise UserError('No audio file attached — upload audio before transcribing.')

        from odoo.addons.language_core.models.rabbitmq_publisher import RabbitMQPublisher  # noqa: PLC0415
        publisher = RabbitMQPublisher(self.env)

        job_id = self._generate_job_id()
        audio_b64 = audio_record.attachment_id.datas
        if isinstance(audio_b64, bytes):
            audio_b64 = audio_b64.decode('utf-8')

        payload = {
            'job_id': job_id,
            'audio_id': audio_record.id,
            'language': audio_record.language,
            'audio_data_b64': audio_b64,
        }
        publisher.publish('audio.transcription.requested', payload, job_id)
        audio_record.sudo().write({
            'transcription_job_id': job_id,
            'transcription_status': 'processing',
            'transcription': False,
            'transcription_error': False,
        })
        _logger.info('audio.transcription.requested published: job_id=%s audio_id=%d',
                     job_id, audio_record.id)
        return audio_record
