{
    'name': 'Language Portal',
    'version': '18.0.1.0.0',
    'category': 'Custom/Lexora',
    'summary': 'Portal views, homepage, posts/articles, copy-to-list inline UI',
    'author': 'Lexora',
    'license': 'LGPL-3',
    'depends': [
        'language_core',
        'language_words',
        'portal',
        'website',
        'website_require_login',
        'website_menu_by_user_status',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/seeded_posts.xml',
        'data/website_menus.xml',
        'views/portal_homepage.xml',
        'views/portal_posts.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
