{
    'name': 'Language Portal',
    'version': '18.0.1.0.0',
    'category': 'Custom/Lexora',
    'summary': 'Portal views, homepage, posts/articles, copy-to-list inline UI',
    'author': 'Lexora',
    'license': 'LGPL-3',
    'depends': [
        'language_core',
        'language_words',
        'portal',
        'website',
        'website_require_login',
        'website_menu_by_user_status',
    ],
    'post_init_hook': 'post_init_hook',
    'post_update_hook': 'post_update_hook',
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/seeded_posts.xml',
        'data/grammar_sections.xml',
        'data/roleplay_scenarios.xml',
        'data/website_menus.xml',
        'views/branding.xml',
        'views/portal_translator.xml',
        'views/portal_homepage.xml',
        'views/portal_posts.xml',
        'views/portal_library.xml',
        'views/portal_roleplay.xml',
        'views/portal_grammar_practice.xml',
        'views/pdf_vocabulary.xml',
        'views/pdf_gold_vocab.xml',
        'views/pdf_grammar.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'language_portal/static/src/js/spotlight.js',
            'language_portal/static/src/css/premium_ui.css',
            'language_portal/static/src/css/print_style.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
