# Generated by Django 5.0 on 2026-03-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_comment_created_at_comment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(help_text='User associated with the progress', on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
