{
    "name": "Lexora Helpdesk",
    "version": "1.0.0",
    "summary": "Minimalist support ticket system with AI RAG auto-reply.",
    "description": """
        Custom Lexora helpdesk with a two-field website form (/support).
        Every new ticket receives an instant OdooBot reply generated by the
        ai_mentor RAG service (pgvector + llama-cpp, CPU-only).
        Authenticated users can view their ticket history at /my/tickets.
    """,
    "author": "Avantgarde Systems",
    "category": "Hidden",
    "license": "LGPL-3",
    "depends": ["website", "mail", "portal"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "views/lexora_ticket_views.xml",
        "views/portal_support.xml",
        "views/portal_tickets.xml",
        "data/ir_config_parameter.xml",
        "data/website_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
