version: "3.8"

services:
  anki-service:
    build:
      context: ../..
      dockerfile: docker_compose/anki/Dockerfile
    container_name: anki_service
    restart: unless-stopped
    ports:
      - "8003:8000"
    networks:
      - backend

networks:
  backend:
    external: true
