{
    'name': 'Language Words',
    'version': '18.0.1.0.0',
    'category': 'Custom/Lexora',
    'summary': 'Learning entries, user profiles, dedup logic, normalization, media links, portal views',
    'author': 'Lexora',
    'license': 'LGPL-3',
    'depends': ['language_core', 'base_search_fuzzy', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/language_lang.xml',
        'data/ir_cron_word_of_day.xml',
        'views/language_entry_views.xml',
        'views/language_user_profile_views.xml',
        'views/portal_vocabulary.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
